services:
  app:
    image: auto_enter_view
    ports:
      - "8080:8080"
    depends_on:
      - mariadb00
      - redis00
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb00:3306/auto_enter_view
      SPRING_DATA_REDIS_HOST: redis00
    networks:
      - app-network

  mariadb00:
    image: mariadb:10.11.8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_DATABASE: auto_enter_view
      MYSQL_USER: aev_user
      MYSQL_PASSWORD: aev_user
    networks:
      - app-network
    command: |
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci

  redis00:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network: